#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvtoAutomation.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TvtoAutomation")]
	public partial class DcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DcDataContext() : 
				base(global::TvtoAutomation.Properties.Settings.Default.TvtoAutomationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_Sign> v_Signs
		{
			get
			{
				return this.GetTable<v_Sign>();
			}
		}
		
		public System.Data.Linq.Table<v_UserPosition> v_UserPositions
		{
			get
			{
				return this.GetTable<v_UserPosition>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentDeleteCommand")]
		public int DocumentDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupDeleteCommand")]
		public int DocumentGroupDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupInsertCommand")]
		public ISingleResult<DocumentGroupInsertCommandResult> DocumentGroupInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<DocumentGroupInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupSelectCommand")]
		public ISingleResult<DocumentGroupSelectCommandResult> DocumentGroupSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DocumentGroupSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupSignDeleteCommand")]
		public int DocumentGroupSignDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_DocumentGroupId", DbType="Int")] System.Nullable<int> original_DocumentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_PositionId", DbType="Int")] System.Nullable<int> original_PositionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_DocumentGroupId, original_PositionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupSignInsertCommand")]
		public ISingleResult<DocumentGroupSignInsertCommandResult> DocumentGroupSignInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentGroupId", DbType="Int")] System.Nullable<int> documentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionId", DbType="Int")] System.Nullable<int> positionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentGroupId, positionId);
			return ((ISingleResult<DocumentGroupSignInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupSignSelectCommand")]
		public ISingleResult<DocumentGroupSignSelectCommandResult> DocumentGroupSignSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DocumentGroupSignSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupSignUpdateCommand")]
		public ISingleResult<DocumentGroupSignUpdateCommandResult> DocumentGroupSignUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentGroupId", DbType="Int")] System.Nullable<int> documentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionId", DbType="Int")] System.Nullable<int> positionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_DocumentGroupId", DbType="Int")] System.Nullable<int> original_DocumentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_PositionId", DbType="Int")] System.Nullable<int> original_PositionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentGroupId, positionId, original_Id, original_DocumentGroupId, original_PositionId, id);
			return ((ISingleResult<DocumentGroupSignUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentGroupUpdateCommand")]
		public ISingleResult<DocumentGroupUpdateCommandResult> DocumentGroupUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, id, original_Id);
			return ((ISingleResult<DocumentGroupUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentInsertCommand")]
		public ISingleResult<DocumentInsertCommandResult> DocumentInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Create", DbType="DateTime")] System.Nullable<System.DateTime> create, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerUsername", DbType="NVarChar(50)")] string ownerUsername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentGroupId", DbType="Int")] System.Nullable<int> documentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, create, ownerUsername, documentGroupId, isDeleted);
			return ((ISingleResult<DocumentInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentSelectCommand")]
		public ISingleResult<DocumentSelectCommandResult> DocumentSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DocumentSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentUpdateCommand")]
		public ISingleResult<DocumentUpdateCommandResult> DocumentUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Create", DbType="DateTime")] System.Nullable<System.DateTime> create, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerUsername", DbType="NVarChar(50)")] string ownerUsername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentGroupId", DbType="Int")] System.Nullable<int> documentGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, create, ownerUsername, documentGroupId, isDeleted, original_Id);
			return ((ISingleResult<DocumentUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionDeleteCommand")]
		public int DocumentVersionDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionInsertCommand")]
		public ISingleResult<DocumentVersionInsertCommandResult> DocumentVersionInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentId", DbType="Int")] System.Nullable<int> documentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Submit", DbType="DateTime")] System.Nullable<System.DateTime> submit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Body", DbType="NVarChar(MAX)")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentId, submit, body, username, isDeleted);
			return ((ISingleResult<DocumentVersionInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionSelectCommand")]
		public ISingleResult<DocumentVersionSelectCommandResult> DocumentVersionSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DocumentVersionSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionSignDeleteCommand")]
		public int DocumentVersionSignDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_DocumentVersionId", DbType="Int")] System.Nullable<int> original_DocumentVersionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_DocumentGroupSignId", DbType="Int")] System.Nullable<int> original_DocumentGroupSignId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Username", DbType="NVarChar(50)")] string original_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Status", DbType="NChar(10)")] string original_Status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Id, original_DocumentVersionId, original_DocumentGroupSignId, original_Username, original_Status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionSignInsertCommand")]
		public ISingleResult<DocumentVersionSignInsertCommandResult> DocumentVersionSignInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentVersionId", DbType="Int")] System.Nullable<int> documentVersionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentGroupSignId", DbType="Int")] System.Nullable<int> documentGroupSignId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentVersionId, documentGroupSignId, username, status);
			return ((ISingleResult<DocumentVersionSignInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionSignSelectCommand")]
		public ISingleResult<DocumentVersionSignSelectCommandResult> DocumentVersionSignSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DocumentVersionSignSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionSignUpdateCommand")]
		public ISingleResult<DocumentVersionSignUpdateCommandResult> DocumentVersionSignUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, original_Id);
			return ((ISingleResult<DocumentVersionSignUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentVersionUpdateCommand")]
		public ISingleResult<DocumentVersionUpdateCommandResult> DocumentVersionUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentId", DbType="Int")] System.Nullable<int> documentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Submit", DbType="DateTime")] System.Nullable<System.DateTime> submit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Body", DbType="NVarChar(MAX)")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, documentId, submit, body, username, isDeleted, original_Id);
			return ((ISingleResult<DocumentVersionUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PositionDeleteCommand")]
		public int PositionDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Name", DbType="NVarChar(50)")] string original_Name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Id, original_Name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PositionInsertCommand")]
		public ISingleResult<PositionInsertCommandResult> PositionInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<PositionInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PositionSelectCommand")]
		public ISingleResult<PositionSelectCommandResult> PositionSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PositionSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PositionUpdateCommand")]
		public ISingleResult<PositionUpdateCommandResult> PositionUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Name", DbType="NVarChar(50)")] string original_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, original_Id, original_Name, id);
			return ((ISingleResult<PositionUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RexaLogin")]
		public ISingleResult<RexaLoginResult> RexaLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(300)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<RexaLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserDeleteCommand")]
		public int UserDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Username", DbType="NVarChar(50)")] string original_Username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserInsertCommand")]
		public ISingleResult<UserInsertCommandResult> UserInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(300)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfilePicture", DbType="VarBinary(MAX)")] System.Data.Linq.Binary profilePicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="NVarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAdmin", DbType="Bit")] System.Nullable<bool> isAdmin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password, profilePicture, firstname, lastname, isDeleted, isAdmin);
			return ((ISingleResult<UserInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserPositionDeleteCommand")]
		public int UserPositionDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Username", DbType="NVarChar(50)")] string original_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_PositionId", DbType="Int")] System.Nullable<int> original_PositionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_Username, original_PositionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserPositionInsertCommand")]
		public ISingleResult<UserPositionInsertCommandResult> UserPositionInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionId", DbType="Int")] System.Nullable<int> positionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, positionId);
			return ((ISingleResult<UserPositionInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserPositionSelectCommand")]
		public ISingleResult<UserPositionSelectCommandResult> UserPositionSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<UserPositionSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserPositionUpdateCommand")]
		public ISingleResult<UserPositionUpdateCommandResult> UserPositionUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionId", DbType="Int")] System.Nullable<int> positionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Id", DbType="Int")] System.Nullable<int> original_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, username, positionId, original_Id);
			return ((ISingleResult<UserPositionUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserSelectCommand")]
		public ISingleResult<UserSelectCommandResult> UserSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<UserSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserUpdateCommand")]
		public ISingleResult<UserUpdateCommandResult> UserUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(300)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfilePicture", DbType="VarBinary(MAX)")] System.Data.Linq.Binary profilePicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="NVarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAdmin", DbType="Bit")] System.Nullable<bool> isAdmin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_Username", DbType="NVarChar(50)")] string original_Username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password, profilePicture, firstname, lastname, isDeleted, isAdmin, original_Username);
			return ((ISingleResult<UserUpdateCommandResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Signs")]
	public partial class v_Sign
	{
		
		private int _SignId;
		
		private int _DocumentVersion;
		
		private int _DocumentId;
		
		private string _DocumentTitle;
		
		private int _DocumentGroupId;
		
		private string _DocumentGroupName;
		
		private int _DocumentGroupSignId;
		
		private int _PositionId;
		
		private string _PositionName;
		
		private string _Username;
		
		private string _Status;
		
		public v_Sign()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignId", DbType="Int NOT NULL")]
		public int SignId
		{
			get
			{
				return this._SignId;
			}
			set
			{
				if ((this._SignId != value))
				{
					this._SignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentVersion", DbType="Int NOT NULL")]
		public int DocumentVersion
		{
			get
			{
				return this._DocumentVersion;
			}
			set
			{
				if ((this._DocumentVersion != value))
				{
					this._DocumentVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentId", DbType="Int NOT NULL")]
		public int DocumentId
		{
			get
			{
				return this._DocumentId;
			}
			set
			{
				if ((this._DocumentId != value))
				{
					this._DocumentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DocumentTitle
		{
			get
			{
				return this._DocumentTitle;
			}
			set
			{
				if ((this._DocumentTitle != value))
				{
					this._DocumentTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DocumentGroupName
		{
			get
			{
				return this._DocumentGroupName;
			}
			set
			{
				if ((this._DocumentGroupName != value))
				{
					this._DocumentGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupSignId", DbType="Int NOT NULL")]
		public int DocumentGroupSignId
		{
			get
			{
				return this._DocumentGroupSignId;
			}
			set
			{
				if ((this._DocumentGroupSignId != value))
				{
					this._DocumentGroupSignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PositionName
		{
			get
			{
				return this._PositionName;
			}
			set
			{
				if ((this._PositionName != value))
				{
					this._PositionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_UserPosition")]
	public partial class v_UserPosition
	{
		
		private string _Username;
		
		private int _PositionId;
		
		private string _Position;
		
		public v_UserPosition()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupInsertCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public DocumentGroupInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupSelectCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public DocumentGroupSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupSignInsertCommandResult
	{
		
		private int _Id;
		
		private int _DocumentGroupId;
		
		private int _PositionId;
		
		public DocumentGroupSignInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupSignSelectCommandResult
	{
		
		private int _Id;
		
		private int _DocumentGroupId;
		
		private int _PositionId;
		
		public DocumentGroupSignSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupSignUpdateCommandResult
	{
		
		private int _Id;
		
		private int _DocumentGroupId;
		
		private int _PositionId;
		
		public DocumentGroupSignUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class DocumentGroupUpdateCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public DocumentGroupUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class DocumentInsertCommandResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private System.DateTime _Create;
		
		private string _OwnerUsername;
		
		private int _DocumentGroupId;
		
		private bool _IsDeleted;
		
		public DocumentInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Create]", Storage="_Create", DbType="DateTime NOT NULL")]
		public System.DateTime Create
		{
			get
			{
				return this._Create;
			}
			set
			{
				if ((this._Create != value))
				{
					this._Create = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OwnerUsername
		{
			get
			{
				return this._OwnerUsername;
			}
			set
			{
				if ((this._OwnerUsername != value))
				{
					this._OwnerUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class DocumentSelectCommandResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private System.DateTime _Create;
		
		private string _OwnerUsername;
		
		private int _DocumentGroupId;
		
		private bool _IsDeleted;
		
		public DocumentSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Create]", Storage="_Create", DbType="DateTime NOT NULL")]
		public System.DateTime Create
		{
			get
			{
				return this._Create;
			}
			set
			{
				if ((this._Create != value))
				{
					this._Create = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OwnerUsername
		{
			get
			{
				return this._OwnerUsername;
			}
			set
			{
				if ((this._OwnerUsername != value))
				{
					this._OwnerUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class DocumentUpdateCommandResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private System.DateTime _Create;
		
		private string _OwnerUsername;
		
		private int _DocumentGroupId;
		
		private bool _IsDeleted;
		
		public DocumentUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Create]", Storage="_Create", DbType="DateTime NOT NULL")]
		public System.DateTime Create
		{
			get
			{
				return this._Create;
			}
			set
			{
				if ((this._Create != value))
				{
					this._Create = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OwnerUsername
		{
			get
			{
				return this._OwnerUsername;
			}
			set
			{
				if ((this._OwnerUsername != value))
				{
					this._OwnerUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupId", DbType="Int NOT NULL")]
		public int DocumentGroupId
		{
			get
			{
				return this._DocumentGroupId;
			}
			set
			{
				if ((this._DocumentGroupId != value))
				{
					this._DocumentGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionInsertCommandResult
	{
		
		private int _Id;
		
		private int _DocumentId;
		
		private System.DateTime _Submit;
		
		private string _Body;
		
		private string _Username;
		
		private bool _IsDeleted;
		
		public DocumentVersionInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentId", DbType="Int NOT NULL")]
		public int DocumentId
		{
			get
			{
				return this._DocumentId;
			}
			set
			{
				if ((this._DocumentId != value))
				{
					this._DocumentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="DateTime NOT NULL")]
		public System.DateTime Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this._Submit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionSelectCommandResult
	{
		
		private int _Id;
		
		private int _DocumentId;
		
		private System.DateTime _Submit;
		
		private string _Body;
		
		private string _Username;
		
		private bool _IsDeleted;
		
		public DocumentVersionSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentId", DbType="Int NOT NULL")]
		public int DocumentId
		{
			get
			{
				return this._DocumentId;
			}
			set
			{
				if ((this._DocumentId != value))
				{
					this._DocumentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="DateTime NOT NULL")]
		public System.DateTime Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this._Submit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionSignInsertCommandResult
	{
		
		private int _Id;
		
		private int _DocumentVersionId;
		
		private int _DocumentGroupSignId;
		
		private string _Username;
		
		private string _Status;
		
		public DocumentVersionSignInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentVersionId", DbType="Int NOT NULL")]
		public int DocumentVersionId
		{
			get
			{
				return this._DocumentVersionId;
			}
			set
			{
				if ((this._DocumentVersionId != value))
				{
					this._DocumentVersionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupSignId", DbType="Int NOT NULL")]
		public int DocumentGroupSignId
		{
			get
			{
				return this._DocumentGroupSignId;
			}
			set
			{
				if ((this._DocumentGroupSignId != value))
				{
					this._DocumentGroupSignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionSignSelectCommandResult
	{
		
		private int _Id;
		
		private int _DocumentVersionId;
		
		private int _DocumentGroupSignId;
		
		private string _Username;
		
		private string _Status;
		
		public DocumentVersionSignSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentVersionId", DbType="Int NOT NULL")]
		public int DocumentVersionId
		{
			get
			{
				return this._DocumentVersionId;
			}
			set
			{
				if ((this._DocumentVersionId != value))
				{
					this._DocumentVersionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupSignId", DbType="Int NOT NULL")]
		public int DocumentGroupSignId
		{
			get
			{
				return this._DocumentGroupSignId;
			}
			set
			{
				if ((this._DocumentGroupSignId != value))
				{
					this._DocumentGroupSignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionSignUpdateCommandResult
	{
		
		private int _Id;
		
		private int _DocumentVersionId;
		
		private int _DocumentGroupSignId;
		
		private string _Username;
		
		private string _Status;
		
		public DocumentVersionSignUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentVersionId", DbType="Int NOT NULL")]
		public int DocumentVersionId
		{
			get
			{
				return this._DocumentVersionId;
			}
			set
			{
				if ((this._DocumentVersionId != value))
				{
					this._DocumentVersionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentGroupSignId", DbType="Int NOT NULL")]
		public int DocumentGroupSignId
		{
			get
			{
				return this._DocumentGroupSignId;
			}
			set
			{
				if ((this._DocumentGroupSignId != value))
				{
					this._DocumentGroupSignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class DocumentVersionUpdateCommandResult
	{
		
		private int _Id;
		
		private int _DocumentId;
		
		private System.DateTime _Submit;
		
		private string _Body;
		
		private string _Username;
		
		private bool _IsDeleted;
		
		public DocumentVersionUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentId", DbType="Int NOT NULL")]
		public int DocumentId
		{
			get
			{
				return this._DocumentId;
			}
			set
			{
				if ((this._DocumentId != value))
				{
					this._DocumentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="DateTime NOT NULL")]
		public System.DateTime Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this._Submit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class PositionInsertCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public PositionInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class PositionSelectCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public PositionSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class PositionUpdateCommandResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public PositionUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class RexaLoginResult
	{
		
		private string _Stauts;
		
		public RexaLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stauts", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Stauts
		{
			get
			{
				return this._Stauts;
			}
			set
			{
				if ((this._Stauts != value))
				{
					this._Stauts = value;
				}
			}
		}
	}
	
	public partial class UserInsertCommandResult
	{
		
		private string _Username;
		
		private string _Password;
		
		private System.Data.Linq.Binary _ProfilePicture;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private bool _IsDeleted;
		
		private bool _IsAdmin;
		
		public UserInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePicture", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary ProfilePicture
		{
			get
			{
				return this._ProfilePicture;
			}
			set
			{
				if ((this._ProfilePicture != value))
				{
					this._ProfilePicture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
	}
	
	public partial class UserPositionInsertCommandResult
	{
		
		private int _Id;
		
		private string _Username;
		
		private int _PositionId;
		
		public UserPositionInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class UserPositionSelectCommandResult
	{
		
		private int _Id;
		
		private string _Username;
		
		private int _PositionId;
		
		public UserPositionSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class UserPositionUpdateCommandResult
	{
		
		private int _Id;
		
		private string _Username;
		
		private int _PositionId;
		
		public UserPositionUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionId", DbType="Int NOT NULL")]
		public int PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
	}
	
	public partial class UserSelectCommandResult
	{
		
		private string _Username;
		
		private string _Password;
		
		private System.Data.Linq.Binary _ProfilePicture;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private bool _IsDeleted;
		
		private bool _IsAdmin;
		
		public UserSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePicture", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary ProfilePicture
		{
			get
			{
				return this._ProfilePicture;
			}
			set
			{
				if ((this._ProfilePicture != value))
				{
					this._ProfilePicture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
	}
	
	public partial class UserUpdateCommandResult
	{
		
		private string _Username;
		
		private string _Password;
		
		private System.Data.Linq.Binary _ProfilePicture;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private bool _IsDeleted;
		
		private bool _IsAdmin;
		
		public UserUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePicture", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary ProfilePicture
		{
			get
			{
				return this._ProfilePicture;
			}
			set
			{
				if ((this._ProfilePicture != value))
				{
					this._ProfilePicture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
